#!/bin/bash
set -e

echo "Removing ForceBindIP..."

# Remove binaries
rm -f /usr/local/bin/forcebindip
rm -f /usr/local/bin/test_ipv4
rm -f /usr/local/bin/test_ipv6

# Remove library
rm -f /usr/local/lib/libforcebindip.so

# Remove documentation
rm -rf /usr/local/share/doc/forcebindip

# Remove man page
rm -f /usr/local/share/man/man1/forcebindip.1

# Update dynamic linker cache
ldconfig

echo "ForceBindIP removed successfully!"

#DEBHELPER#

exit 0
